#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/hunyuan_vl/modular_hunyuan_vl.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_hunyuan_vl.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright (C) 2026 THL A29 Limited, a Tencent company and the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig
from ...modeling_rope_utils import RopeParameters
from ...utils import auto_docstring


@auto_docstring(
    custom_intro="""
    Vision backbone configuration for the dense-only, image-text HunYuanVL open-source variant.
    """,
    checkpoint="tencent/HunyuanOCR",
)
@strict
class HunYuanVLVisionConfig(PreTrainedConfig):
    r"""
    interpolate_mode (`str`, *optional*, defaults to `"bilinear"`):
        Interpolation mode used when resizing learned patch positional embeddings to match the current image grid.
    learnable_mlp_pooling_size (`int`, *optional*, defaults to 0):
        Optional learnable pooling size for the vision tower.
    out_hidden_size (`int`, *optional*, defaults to 4096):
        Output hidden size produced by the vision tower before it is consumed by the text backbone.
    remove_prenorm (`bool`, *optional*, defaults to `True`):
        Whether to remove the pre-normalization behavior used by some internal vision variants.
    resize_resolution (`int`, *optional*, defaults to 2048):
        Reference resolution used when deriving image resizing and tokenization behavior.
    img_max_token_num (`int`, *optional*, defaults to 4096):
        Maximum image token count expected by the vision stack.
    max_image_size (`int`, *optional*, defaults to 2048):
        Maximum supported image size for the current open-source vision configuration.
    min_image_size (`int`, *optional*, defaults to 512):
        Minimum supported image size for the current open-source vision configuration.
    anyres_vit_max_image_size (`int`, *optional*, defaults to 2048):
        Maximum image size supported by the any-resolution vision preprocessing path.
    max_vit_seq_len (`int`, *optional*, defaults to 16384):
        Maximum sequence length produced by the vision transformer.
    text_hidden_size (`int`, *optional*, defaults to 3072):
        Hidden size expected by the text backbone when consuming visual embeddings.

    Example:

    ```python
    >>> from transformers import HunYuanVLVisionConfig
    >>>
    >>> configuration = HunYuanVLVisionConfig()
    >>> configuration.hidden_size
    1152
    ```"""

    model_type = "hunyuan_vl_vision"
    base_config_key = "vision_config"

    hidden_act: str = "gelu"
    hidden_size: int = 1152
    intermediate_size: int = 4304
    interpolate_mode: str = "bilinear"
    rms_norm_eps: float = 1e-5
    learnable_mlp_pooling_size: int = 0
    attention_dropout: float = 0.0
    num_attention_heads: int = 16
    num_key_value_heads: int | None = None
    num_channels: int = 3
    num_hidden_layers: int = 27
    out_hidden_size: int = 4096
    patch_size: int = 16
    remove_prenorm: bool = True
    spatial_merge_size: int = 2
    temporal_patch_size: int = 1
    resize_resolution: int = 2048
    img_max_token_num: int = 4096
    max_image_size: int = 2048
    min_image_size: int = 512
    anyres_vit_max_image_size: int = 2048
    max_vit_seq_len: int = 16384
    text_hidden_size: int = 3072

    def __post_init__(self, **kwargs):
        if not self.num_key_value_heads:
            self.num_key_value_heads = self.num_attention_heads
        super().__post_init__(**kwargs)


@auto_docstring(
    custom_intro="""
    Text backbone configuration for the dense-only, image-text HunYuanVL open-source variant.

    Inherits the standard fields from [`HunYuanDenseV1Config`]. A few legacy field names that some Tencent checkpoints
    persist on disk (`pad_id`, `attention_head_dim`, `org_vocab_size`) are exposed as `attribute_map` aliases that
    transparently redirect to the canonical `pad_token_id` / `head_dim` / `vocab_size` slots. The legacy `rope_scaling`
    / `rope_theta` keys are folded into the standardized `rope_parameters` dict by `convert_rope_params_to_dict`.
    """,
    checkpoint="tencent/HunyuanOCR",
)
@strict
class HunYuanVLTextConfig(PreTrainedConfig):
    r"""
    eod_token_id (`int`, *optional*, defaults to 3):
        Token id representing the end-of-document marker. Inherited from [`HunYuanDenseV1Config`] and re-documented
        here so the auto-generated docstring stays in sync.
    sep_token_id (`int`, *optional*, defaults to 4):
        Token id used as a separator marker by HunYuan tokenizers.
    tie_word_embeddings (`bool`, *optional*, defaults to `True`):
        Whether to tie the input and output word embeddings.
    use_qk_norm (`bool`, *optional*, defaults to `False`):
        Legacy flag preserved for checkpoint compatibility. Has no runtime effect in the open-source variant.
    use_cla (`bool`, *optional*, defaults to `False`):
        Legacy flag preserved for checkpoint compatibility. Has no runtime effect in the open-source variant.
    enable_lm_head_fp32 (`bool`, *optional*, defaults to `False`):
        Legacy flag preserved for checkpoint compatibility. Has no runtime effect in the open-source variant.
    """

    model_type = "hunyuan_vl_text"
    keys_to_ignore_at_inference = ["past_key_values"]

    vocab_size: int = 290943
    hidden_size: int = 4096
    intermediate_size: int = 11008
    num_hidden_layers: int = 32
    num_attention_heads: int = 32
    num_key_value_heads: int | None = None
    hidden_act: str = "silu"
    max_position_embeddings: int = 2048
    initializer_range: float = 0.02
    rms_norm_eps: float = 1e-5
    use_cache: bool = True
    pad_token_id: int | None = 0
    bos_token_id: int | None = 1
    eos_token_id: int | list[int] | None = 2
    eod_token_id: int | None = 3
    pretraining_tp: int = 1
    tie_word_embeddings: bool = True
    rope_parameters: RopeParameters | dict | None = None
    attention_bias: bool = False
    attention_dropout: float | int = 0.0
    head_dim: int | None = None
    base_config_key = "text_config"
    # Legacy Tencent-export config keys -> canonical field names. ``attribute_map`` is a pure key alias, so reading or
    # writing the legacy name transparently redirects to the canonical attribute (see `PreTrainedConfig.__setattr__`).
    attribute_map = {
        "pad_id": "pad_token_id",
        "attention_head_dim": "head_dim",
        "org_vocab_size": "vocab_size",
    }
    # ``xdrope`` carries scaling knobs (alpha/beta/mscale) and a section layout that the generic rope validator does
    # not know about; whitelist them so validation does not raise (the rope type is standardized to ``dynamic``).
    ignore_keys_at_rope_validation = {
        "alpha",
        "beta_fast",
        "beta_slow",
        "mscale",
        "mscale_all_dim",
        "xdrope_section",
    }

    sep_token_id: int | None = 4
    use_qk_norm: bool = False
    use_cla: bool = False
    enable_lm_head_fp32: bool = False

    def __post_init__(self, **kwargs):
        # Some Tencent checkpoints persist both ``pad_id`` (the real id) and ``pad_token_id: -1`` (a sentinel). Because
        # ``pad_id`` is now an ``attribute_map`` alias of ``pad_token_id`` the two collide, so explicitly prefer the
        # real value when the canonical slot still holds the ``-1`` sentinel.
        pad_id = kwargs.pop("pad_id", None)
        if self.pad_token_id == -1 and pad_id not in (None, -1):
            self.pad_token_id = pad_id
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads
        super().__post_init__(**kwargs)

    def convert_rope_params_to_dict(self, **kwargs):
        # Fold the legacy ``rope_scaling`` / ``rope_theta`` keys into the standardized ``rope_parameters`` dict and
        # rewrite HunYuan's ``xdrope`` rope type to the generic ``dynamic`` type the runtime understands. Always
        # produce a populated ``rope_parameters`` (defaulting to a plain ``default`` rope) so the rotary embedding
        # always has a ``rope_type`` to read, matching the base config behavior.
        rope_scaling = kwargs.pop("rope_scaling", None)
        self.rope_parameters = rope_scaling or self.rope_parameters or {}
        self.rope_parameters = dict(self.rope_parameters)
        rope_type = self.rope_parameters.get("rope_type", self.rope_parameters.get("type", "default"))
        if rope_type == "xdrope":
            rope_type = "dynamic"
        self.rope_parameters["rope_type"] = rope_type
        self.rope_parameters.setdefault("rope_theta", kwargs.pop("rope_theta", self.default_theta))
        self.standardize_rope_params()
        return kwargs

    @property
    def xdrope_num_sections(self) -> int:
        """Number of position-id channels used by xdrope (e.g. 4 for `[text, w, h, t]`)."""
        rope_parameters = getattr(self, "rope_parameters", None) or {}
        xdrope_section = rope_parameters.get("xdrope_section")
        return len(xdrope_section) if xdrope_section else 4


@auto_docstring(
    custom_intro="""
    Top-level configuration for the open-source HunYuanVL integration.

    This configuration describes the dense-only, image-text-only variant used for OCR and document-understanding style
    workloads. It mirrors the `Qwen2_5_VL` / `Qwen3_VL` family layout: the top-level config simply composes a
    [`HunYuanVLTextConfig`] (text backbone) and a [`HunYuanVLVisionConfig`] (vision tower) plus a few token ids that
    delimit image spans in multimodal prompts.
    """,
    checkpoint="tencent/HunyuanOCR",
)
@strict
class HunYuanVLConfig(PreTrainedConfig):
    r"""
    text_config (`HunYuanVLTextConfig` or `dict`, *optional*):
        Configuration of the text backbone. When `None`, default values are used.
    vision_config (`HunYuanVLVisionConfig` or `dict`, *optional*):
        Configuration of the vision tower. When `None`, default values are used.
    image_token_id (`int`, *optional*, defaults to 120120):
        Token id used as the visual placeholder in multimodal prompts.
    im_start_id (`int`, *optional*, defaults to 120118):
        Token id marking the beginning of an image span in multimodal prompts.
    im_end_id (`int`, *optional*, defaults to 120119):
        Token id marking the end of an image span in multimodal prompts.
    im_newline_id (`int`, *optional*, defaults to 120121):
        Token id used for newline-style separators inserted inside serialized image regions.
    tie_word_embeddings (`bool`, *optional*, defaults to `True`):
        Whether to tie the input and output word embeddings.

    Example:

    ```python
    >>> from transformers import HunYuanVLConfig, HunYuanVLForConditionalGeneration
    >>>
    >>> configuration = HunYuanVLConfig()
    >>> model = HunYuanVLForConditionalGeneration(configuration)
    >>> configuration = model.config
    ```"""

    model_type = "hunyuan_vl"
    sub_configs = {"vision_config": HunYuanVLVisionConfig, "text_config": HunYuanVLTextConfig}
    keys_to_ignore_at_inference = ["past_key_values"]
    # Legacy Tencent-export config keys -> canonical field names (released config.json uses the longer spellings).
    attribute_map = {
        "image_start_token_id": "im_start_id",
        "image_end_token_id": "im_end_id",
        "image_newline_token_id": "im_newline_id",
    }

    text_config: dict | PreTrainedConfig | None = None
    vision_config: dict | PreTrainedConfig | None = None
    image_token_id: int = 120120
    im_start_id: int = 120118
    im_end_id: int = 120119
    im_newline_id: int = 120121
    tie_word_embeddings: bool = True

    def __post_init__(self, **kwargs):
        # When loading legacy "flat" Tencent checkpoints (where text fields live at the top level instead of inside a
        # nested `text_config` block) we fold the recognized text-side keys into the text config payload. This keeps
        # ``HunYuanVLConfig.from_pretrained(...)`` working with both the upstream nested layout and the existing
        # public OCR checkpoints.
        text_kwargs = self._extract_text_kwargs(kwargs)

        if isinstance(self.vision_config, dict):
            self.vision_config = self.sub_configs["vision_config"](**self.vision_config)
        elif self.vision_config is None:
            self.vision_config = self.sub_configs["vision_config"]()

        if isinstance(self.text_config, dict):
            self.text_config = self.sub_configs["text_config"](**{**self.text_config, **text_kwargs})
        elif self.text_config is None:
            self.text_config = self.sub_configs["text_config"](**text_kwargs)

        # Keep the vision tower in sync with the consuming text backbone size.
        self.vision_config.text_hidden_size = self.text_config.hidden_size

        super().__post_init__(**kwargs)

    @classmethod
    def _extract_text_kwargs(cls, kwargs: dict) -> dict:
        """
        Pop and return the subset of ``kwargs`` that should be forwarded to [`HunYuanVLTextConfig`].

        Required to support legacy Tencent checkpoints whose ``config.json`` stores the text-backbone fields at the
        top level instead of inside a nested ``text_config`` block. Besides the canonical text fields, this also
        captures the legacy alias keys (`pad_id` / `attention_head_dim` / `org_vocab_size`) and the legacy rope keys
        (`rope_scaling` / `rope_theta`) so they reach the text config where they are normalized.
        """
        text_cfg = cls.sub_configs["text_config"]
        text_keys = (
            set(text_cfg.__dataclass_fields__)
            | set(getattr(text_cfg, "attribute_map", {}))
            | {"rope_scaling", "rope_theta"}
        )
        return {key: kwargs.pop(key) for key in list(kwargs) if key in text_keys}


__all__ = ["HunYuanVLConfig", "HunYuanVLVisionConfig", "HunYuanVLTextConfig"]
